const users = [{
    name: "aston",
    level: 100,
    decks: [{
        name: "Test Deck 01", 
        deck: [[
            "Dotscaper", 
            "Micro Coder",
            "Micro Coder",
            "Micro Coder",
            "Cyberse Synchron", 
            "Cyberse Converter", 
            "Knightmare Corruptor Iblee", 
            "Ash Blossom & Joyous Spring", 
            "Ash Blossom & Joyous Spring", 
            "Ash Blossom & Joyous Spring", 
            "Backup Secretary", 
            "Code Generator", 
            "Lady Debug", 
            "Lady Debug", 
            "Lady Debug", 
            "Clock Wyvern",
            "Clock Wyvern",
            "Linkslayer",
            "Parallel eXceed", 
            "Parallel eXceed",
            "Nibiru, the Primal Being", 
            "Cyberse Sage",
            "Raigeki",
            "Monster Reborn",
            "One-Time Passcode",
            "Cynet Fusion",
            "Cynet Mining",
            "Cynet Mining",
            "Cynet Storm", 
            "Cynet Ritual", 
            "Cynet Optimization", 
            "Cynet Optimization", 
            "Cynet Codec", 
            "Cynet Codec", 
            "Forbidden Droplet", 
            "Infinite Impermanence", 
            "Infinite Impermanence", 
            "Backup Team", 
            "Cynet Circuit", 
            "Cynet Conflict"
        ], [
            "Cyberse Clock Dragon", 
            "Cyberse Quantum Dragon", 
            "Firewall eXceed Dragon", 
            "Link Decoder", 
            "Code Talker", 
            "Code Talker Inverted", 
            "I:P Masquerena", 
            "Splash Mage", 
            "Tri-Gate Wizard", 
            "Transcode Talker", 
            "Decode Talker Heatsoul", 
            "Firewall Dragon", 
            "Mekk-Knight Crusadia Avramax", 
            "Apollousa, Bow of the Goddess", 
            "Accesscode Talker"
        ],]
    }],
    active: {
        level: 100,
        deck: []
    }
}, {
    name: "Rakkshas",
    level: 1,
    decks: [{
        name: "", 
        deck: [[
            "Kazejin",
            "Kazejin",
            "Suijin",
            "Suijin",
            "Sanaga of the Thunder",
            "Sanaga of the Thunder",
            "Labyrinth Heavy Tank",
            "Labyrinth Heavy Tank",
            "Labyrinth Heavy Tank",
            "Shadow Ghoul of the Labyrinth",
            "Shadow Ghoul of the Labyrinth",
            "Shadow Ghoul of the Labyrinth",
            "Ash Blossom & Joyous Spring",
            "Ash Blossom & Joyous Spring",
            "Ash Blossom & Joyous Spring",
            "Elemental Hero Prisma",
            "Elemental Hero Prisma",
            "Elemental Hero Prisma",
            "Magician's Soul",
            "Magician's Soul",
            "Dark Guardian",
            "Labyrinth Wall Shadow",
            "Labyrinth Wall Shadow",
            "Labyrinth Wall Shadow",
            "Double Attack Wind and Thunder!",
            "Double Attack Wind and Thunder!",
            "Double Attack Wind and Thunder!",
            "Riryoku Guardian",
            "Foolish Burial",
            "Foolish Burial Goods",
            "A Hero Lives",
            "Fusion Deployment",
            "Burial From a Different Dimension",
            "Burial From a Different Dimension",
            "Forbidden Droplet",
            "Forbidden Droplet",
            "Forbidden Droplet",
            "Dark Element",
            "Dark Element",
            "Dark Element",
            "Prey of Jirai Gumo"
        ], [
            "Gate Guardian of Thunder and Wind",
            "Gate Guardian of Thunder and Wind",
            "Gate Guardian of Thunder and Wind",
            "Gate Guardian of Wind and Water",
            "Gate Guardian of Wind and Water",
            "Gate Guardian of Wind and Water",
            "Gate Guardian of Thunder and Water",
            "Gate Guardian of Thunder and Water",
            "Gate Guardian of Thunder and Water",
            "Gate Guardians Combined",
            "Gate Guardians Combined",
            "Gate Guardians Combined",
            "Relinquished Anima",
            "Knightmare Phoenix",
            "Big Eye"
        ]]
    }]
}, {
    name: "Mekk-Knight Red Moon",
    level: 0,
}]